library(dplyr)
a<-read.csv("household_power_consumption.txt",sep=";",colClasses="character",header=TRUE)
b<-subset(a,a$Date=="1/2/2007")
c<-subset(a,a$Date=="2/2/2007")
data<-rbind(b,c)
data<-mutate(data,DT=paste(Date,Time))
data$DT<-strptime(data$DT,"%d/%m/%Y %H:%M:%S")
data[,1]<-as.Date(data[,1],"%d/%m/%Y")
data[,3]<-as.numeric(data[,3])
data[,7]<-as.numeric(data[,7])
data[,8]<-as.numeric(data[,8])
data[,9]<-as.numeric(data[,9])
y<-range(c(data$Sub_metering_1,data$Sub_metering_2,data$Sub_metering_3))
png("plot3.png",width=480,height=480,units="px")
with(data,plot(DT,Sub_metering_1,type="l",ylim=y,xlab="",ylab=""))
with(data,lines(DT,Sub_metering_2,col="red"))
with(data,lines(DT,Sub_metering_3,col="blue"))
title(ylab="Energy sub metering")
x<-c("sub_metering_1","sub_metering_2","sub_metering_3")
legend("topright",x,pch="_",col=c("black","red","blue"))
dev.off()


