library(dplyr)
a<-read.csv("household_power_consumption.txt",sep=";",colClasses="character",header=TRUE)
b<-subset(a,a$Date=="1/2/2007")
c<-subset(a,a$Date=="2/2/2007")
data<-rbind(b,c)
data<-mutate(data,DT=paste(Date,Time))
data[,1]<-as.Date(data[,1],"%d/%m/%Y")
data[,3]<-as.numeric(data[,3])
data$DT<-strptime(data$DT,"%d/%m/%Y %H:%M:%S")
png("plot2.png",width=480,height=480,units="px")
with(data,plot(DT,Global_active_power,type="l",xlab="",ylab="Global Active Power(kilowatts)"))
dev.off()